"""
Test harness for the collector logic.

``openai_usage_helper`` imports three things that only exist inside a Splunk
installation: ``import_declare_test`` (generated by ucc-gen), ``solnlib`` and
``splunklib``.  None of them are needed to exercise the collectors, whose
``format_record()`` methods are pure functions over API response dicts.  We
stub them into ``sys.modules`` before the import so the module loads outside
Splunk.

The fixtures below are shaped from OpenAI's published OpenAPI schemas
(``openai/openai-openapi``, ``components.schemas.Usage*Result``), not from
what the collector happens to read.  That is the point: the previous field
names were invented and the tests need an independent source of truth.
"""

import sys
import types
from pathlib import Path

import pytest

PACKAGE_BIN = Path(__file__).resolve().parent.parent / "package" / "bin"


def _stub_splunk_modules() -> None:
    sys.modules.setdefault("import_declare_test", types.ModuleType("import_declare_test"))

    solnlib = types.ModuleType("solnlib")
    for name in ("checkpointer", "conf_manager", "log"):
        sub = types.ModuleType(f"solnlib.{name}")
        setattr(solnlib, name, sub)
        sys.modules[f"solnlib.{name}"] = sub
    solnlib.log.Logs = lambda: types.SimpleNamespace(get_logger=lambda _n: None)
    sys.modules.setdefault("solnlib", solnlib)

    splunklib = types.ModuleType("splunklib")
    modularinput = types.ModuleType("splunklib.modularinput")

    # The module annotates its entry points with smi.ValidationDefinition,
    # smi.Script and friends at def-time.  Hand back a throwaway class for any
    # attribute rather than enumerating the SDK surface.
    def _any_attr(name):
        if name.startswith("__"):
            raise AttributeError(name)
        return type(name, (), {})

    modularinput.__getattr__ = _any_attr
    splunklib.modularinput = modularinput
    sys.modules.setdefault("splunklib", splunklib)
    sys.modules.setdefault("splunklib.modularinput", modularinput)


_stub_splunk_modules()
sys.path.insert(0, str(PACKAGE_BIN))


@pytest.fixture
def helper():
    import openai_usage_helper

    return openai_usage_helper


class RecordingSession:
    """Captures the params of each request instead of making one."""

    def __init__(self, pages):
        self.pages = list(pages)
        self.calls = []

    def get(self, url, headers=None, params=None, proxies=None, timeout=None):
        self.calls.append({"url": url, "params": dict(params or {})})
        body = self.pages.pop(0) if self.pages else {"data": [], "has_more": False}
        return types.SimpleNamespace(
            status_code=200,
            headers={},
            json=lambda: body,
            text="",
        )


@pytest.fixture
def recording_session():
    return RecordingSession
