[openai_api_usage]
search   = sourcetype="openai:usage" status!=error
priority = 1

[openai_api_usage_completions]
search   = sourcetype="openai:usage" endpoint_type=completions status!=error
priority = 2

[openai_api_usage_embeddings]
search   = sourcetype="openai:usage" endpoint_type=embeddings status!=error
priority = 2

[openai_api_usage_error]
search   = sourcetype="openai:usage" status=error
priority = 1
