[eventtype=openai_api_usage]
cloud = enabled
api   = enabled

[eventtype=openai_api_usage_completions]
cloud = enabled
api   = enabled

[eventtype=openai_api_usage_embeddings]
cloud = enabled
api   = enabled

[eventtype=openai_api_usage_error]
cloud = enabled
api   = enabled
error = enabled
